### ISSUE TITLE
你好，我需要能够设置module

### ISSUE THREAD

**Issue by philipxiaoxi** [Ftrybe/vue-typescript-files#9]
你好，我需要能够设置module，希望能够支持。现在只能是`scope`

**Comment by Ftrybe** [comment]
举个例子

**Comment by philipxiaoxi** [comment]
> 举个例子

你好，例如style当中可以使用scoped 也可也使用 module ，针对这部分希望能够可以自定义，我看了一下源码，在模板当中是写死了，希望您能抽空增加一下，非常感谢！
![image](https://user-images.githubusercontent.com/52746230/188040043-f617a117-9a8b-4a90-88ae-0e9e877a74e3.png)

![image](https://user-images.githubusercontent.com/52746230/188040085-b9162d81-e474-49d4-bfb6-d8051a3ec8a2.png)

**Comment by Ftrybe** [comment]
OK ,更新下
